spring:
  application:
    name: spring-product-service
  datasource:
    url: jdbc:postgresql://localhost:54320/meetup
    username: meetup
    password: meetup

# Actuator
management:
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# App Info
info:
  spring-product-service:
    application.name: "@project.artifactId@"
    build.version: "@project.version@"
    build.timestamp: "@maven.build.timestamp@"
